security:
    providers:
        in_memory:
            memory:
                users:
                    test: { password: 'test123', roles: ['ROLE_USER'] }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/v1/token$
            stateless: true
            anonymous: true
            provider: in_memory
            json_login:
                check_path: api_login_check
                username_path: security.credentials.username
                password_path: security.credentials.password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern: ^/v1
            stateless: true
            anonymous: true
            provider: in_memory
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

    access_control:
        - { path: ^/v1/token, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/v1, roles: IS_AUTHENTICATED_ANONYMOUSLY }
