security:
    encoders:
        App\Entity\Auth:
            algorithm: bcrypt
            cost: 8

    providers:
        dbusers:
            entity:
                class: App\Entity\Auth
                property: username

    firewalls:
        login:
            pattern:  ^/v1/login$
            stateless: true
            anonymous: true
            json_login:
                check_path: /v1/login
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        register:
            pattern:  ^/v1/register$
            stateless: true
            anonymous: true

        api:
            pattern:  ^/v1
            stateless: true
            anonymous: false
            provider: dbusers
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

    access_control:
        - { path: ^/v1/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/v1/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/v1,       roles: IS_AUTHENTICATED_FULLY }
