api_login_check:
    path: /v1/login
    methods: [POST]

get_user:
    path: /v1/user
    controller: App\Controller\UserController:getUserDetails
    methods: [GET]

get_timetables:
    path: /v1/timetables/{profileId}
    controller: App\Controller\TimetableController::getProfileTimetable
    methods: [GET]

get_user_profiles:
    path: /v1/profiles
    controller: App\Controller\ProfileController::getUserProfiles
    methods: [GET]

get_single_profile:
    path: /v1/profiles/{profileId}
    controller: App\Controller\ProfileController::getProfile
    methods: [GET]

create_profile:
    path: /v1/profiles
    controller: App\Controller\ProfileController::createProfile
    methods: [POST]

edit_profile:
    path: /v1/profiles/{profileId}
    controller: App\Controller\ProfileController::pathProfile
    methods: [PATCH]

get_examinations_list:
    path: /v1/examinations
    controller: App\Controller\ExaminationController::getList
    methods: [GET]